### ISSUE TITLE
LocalNLPBackend queries GPS all the time even if Active Mode is off 

### ISSUE THREAD

**Issue by Jonny007-MKD** [Helium314/Local-NLP-Backend#27] opened 2024-10-02 16:14 UTC
Moin,

I really like the idea of this app. I also understand the necessity to fill a database using GPS. But I installed the app some weeks ago and it still uses GPS like every minute or so, and it drains the battery noticeably. Setting the Active Mode to Low or even to Off does not help; GPS is stilled used.

Is this intended? To my understanding the app should not use GPS at all if the Active Mode is Off.

**Comment by Helium314** [comment] 2024-10-02 16:43
How do you tell whether LocalNLPBackend is using GPS? I remember there was something related in another issue.

**Comment by Helium314** [comment] 2024-10-03 18:56
Alright, then it's a duplicate of #2.

**Closed by Helium314** 2024-10-03 18:56 UTC
